export type Language = 'de' | 'en';

type Bilingual = Record<Language, string>;

export const portfolioCopy = {
  de: {
    nav: ['Start', 'Projekte', 'Kompetenzen', 'Über mich', 'Berufserfahrung', 'Qualifikationen', 'Kontakt'],
    navLabel: 'Hauptnavigation',
    homeLabel: 'Startseite von Yasser Akanni',
    openRoles: 'Offen für Junior-Positionen',
    location: 'Essen, Deutschland · Ruhrgebiet · NRW',
    role: 'Junior Frontend-Entwickler',
    stack: 'React · Next.js · TypeScript',
    headline: ['Durchdachte Interfaces.', 'Systeme, die funktionieren.'],
    hero: 'Ich entwickle responsive Webanwendungen mit React, Next.js und TypeScript und verbinde moderne Frontend-Entwicklung mit UI/UX-Denken und praktischer Full-Stack-Erfahrung.',
    viewWork: 'Projekte ansehen',
    downloadCv: 'Lebenslauf herunterladen',
    lookingFor: 'Gesuchte Positionen',
    roles: 'Junior Frontend-Entwickler · React-Entwickler · Next.js-Entwickler · Webentwickler',
    preferred: 'Essen · Duisburg · Düsseldorf · Dortmund · NRW',
    processTitle: 'So arbeite ich',
    primaryFocus: 'Primärer Fokus',
    frontendDevelopment: 'Frontend-Entwicklung',
    projectsKicker: 'Ausgewählte Projekte',
    projectsTitle: ['Frontend im Fokus.', 'Full-Stack mitgedacht.'],
    projectsIntro: 'Drei Projekte zeigen meine Arbeit mit modernen Frontends, Daten, Authentifizierung und klaren digitalen Abläufen.',
    liveDemo: 'Live-Demo',
    sourceCode: 'GitHub',
    caseStudy: 'Kompakte Fallstudie',
    problem: 'Problem',
    contribution: 'Mein Beitrag',
    decision: 'Technische Entscheidung',
    implemented: 'Umgesetzte Funktionen',
    architecture: 'Architektur',
    skillsKicker: 'Technische Kompetenzen',
    skillsTitle: 'Werkzeuge für den Weg von der Idee zum funktionierenden Produkt.',
    skillsIntro: 'Projektbasierte Erfahrung entlang des gesamten Entwicklungsprozesses.',
    evidence: 'Projektnachweis',
    aboutKicker: 'Über mich',
    aboutTitle: ['Ein Karrierewechsel,', 'aber kein Neuanfang bei null.'],
    aboutLead: 'Vor meinem Wechsel in die IT war ich im Einkaufsmanagement, in der internationalen Beschaffung und in der Logistik tätig. Diese Erfahrung prägt meine Arbeit bis heute.',
    aboutBody: 'Beschaffung bedeutete Lieferanten zu koordinieren, klar zu kommunizieren und Geschäftsprozesse zuverlässig zu begleiten. SAP und Einkaufsdaten schärften meinen Blick für strukturierte Informationen. In der Logistik lernte ich, auch unter Zeitdruck sicher, verlässlich und lösungsorientiert zu handeln.',
    aboutTraining: 'Am Syntax Institut verbinde ich diese Berufserfahrung mit aktueller, projektbasierter Praxis in Frontend-Entwicklung, UI/UX, Backend-Grundlagen, Datenbanken und Deployment.',
    perspective: 'Meine Arbeitsweise',
    perspectiveBody: 'Nutzerproblem verstehen, Ablauf gestalten, Interface entwickeln und die Systeme dahinter sauber anbinden.',
    experienceKicker: 'Berufserfahrung & Qualifizierung',
    experienceTitle: ['Technischer Fokus.', 'Berufliche Disziplin.'],
    experienceIntro: 'Meine Projekte zeigen meine aktuelle Entwicklungspraxis. Frühere Rollen ergänzen sie um Prozessverständnis, Verantwortung und Zusammenarbeit.',
    qualificationsKicker: 'Qualifikationen',
    qualificationsTitle: 'Nachgewiesene Weiterbildung für digitale Produkte und Webentwicklung.',
    qualificationsIntro: 'Öffentliche Webversionen der Dokumente sind aus Datenschutzgründen ohne Geburtsdatum bereitgestellt.',
    certificate: 'Zertifikat',
    viewCertificate: 'Zertifikat ansehen',
    applicationKicker: 'Bewerbungsprofil',
    applicationTitle: 'Frontend-Positionen im Ruhrgebiet und in NRW.',
    applicationLabels: ['Standort', 'Wunschregionen', 'Zielrollen', 'Sprachen'],
    applicationValues: [
      'Essen · Ruhrgebiet · NRW',
      'Essen · Duisburg · Düsseldorf · Dortmund · NRW',
      'Junior Frontend-Entwickler · React-Entwickler · Next.js-Entwickler · Webentwickler',
      'Englisch – fließend · Französisch – fließend · Deutsch – im Aufbau',
    ],
    contactKicker: 'Kontakt',
    contactTitle: 'Lassen Sie uns etwas Nützliches entwickeln.',
    contactBody: 'Ich suche eine Junior-Position im Frontend- oder Webentwicklungsbereich, in der ich an echten Produkten mitarbeiten, von erfahrenen Entwicklerinnen und Entwicklern lernen und mich als Frontend Engineer weiterentwickeln kann.',
    privacy: 'Der Kontakt öffnet Ihre E-Mail-App. Auf dieser Website werden keine Formulardaten gespeichert.',
    backToTop: 'Nach oben',
    cvLabel: 'Lebenslauf (Englisch)',
  },
  en: {
    nav: ['Home', 'Projects', 'Skills', 'About', 'Experience', 'Qualifications', 'Contact'],
    navLabel: 'Main navigation',
    homeLabel: 'Yasser Akanni home',
    openRoles: 'Open to junior roles',
    location: 'Essen, Germany · Ruhrgebiet · NRW',
    role: 'Junior Frontend Developer',
    stack: 'React · Next.js · TypeScript',
    headline: ['Interfaces with intent.', 'Systems that work.'],
    hero: 'I build responsive web applications with React, Next.js, and TypeScript, combining frontend engineering with UI/UX thinking and practical full-stack experience.',
    viewWork: 'View my work',
    downloadCv: 'Download CV',
    lookingFor: 'Currently looking for',
    roles: 'Junior Frontend Developer · React Developer · Next.js Developer · Web Developer',
    preferred: 'Essen · Duisburg · Düsseldorf · Dortmund · NRW',
    processTitle: 'How I build',
    primaryFocus: 'Primary focus',
    frontendDevelopment: 'Frontend development',
    projectsKicker: 'Selected work',
    projectsTitle: ['Frontend craft.', 'Full-stack thinking.'],
    projectsIntro: 'Three projects show my work with modern frontends, data, authentication, and clear digital workflows.',
    liveDemo: 'Live demo',
    sourceCode: 'GitHub',
    caseStudy: 'Compact case study',
    problem: 'Problem',
    contribution: 'My contribution',
    decision: 'A technical decision',
    implemented: 'Implemented functionality',
    architecture: 'Architecture',
    skillsKicker: 'Technical skills',
    skillsTitle: 'Tools I use to move from idea to working product.',
    skillsIntro: 'Practical, project-based experience across the web application lifecycle.',
    evidence: 'Project evidence',
    aboutKicker: 'About',
    aboutTitle: ['A career change,', 'not a blank slate.'],
    aboutLead: 'Before moving into technology, I worked in purchasing management, international procurement, and logistics operations. That experience still shapes how I work today.',
    aboutBody: 'Procurement required supplier coordination, clear business communication, and dependable processes. SAP and purchasing records strengthened my awareness of structured data. Logistics taught me to work safely, reliably, and calmly under operational deadlines.',
    aboutTraining: 'At Syntax Institut, I connect that professional experience with current project-based practice in frontend development, UI/UX, backend fundamentals, databases, and deployment.',
    perspective: 'My perspective',
    perspectiveBody: 'Understand the user problem, shape the flow, build the interface, and connect it cleanly to the systems behind it.',
    experienceKicker: 'Experience & training',
    experienceTitle: ['Technical direction.', 'Professional discipline.'],
    experienceIntro: 'My projects show my current development practice. Earlier roles add process awareness, responsibility, and teamwork.',
    qualificationsKicker: 'Qualifications',
    qualificationsTitle: 'Verified training in digital products and web development.',
    qualificationsIntro: 'Public web copies of the documents omit the date of birth for privacy.',
    certificate: 'Certificate',
    viewCertificate: 'View certificate',
    applicationKicker: 'Application profile',
    applicationTitle: 'Frontend opportunities in the Ruhrgebiet and across NRW.',
    applicationLabels: ['Location', 'Preferred locations', 'Target roles', 'Languages'],
    applicationValues: [
      'Essen · Ruhrgebiet · NRW',
      'Essen · Duisburg · Düsseldorf · Dortmund · NRW',
      'Junior Frontend Developer · React Developer · Next.js Developer · Web Developer',
      'English – fluent · French – fluent · German – currently developing',
    ],
    contactKicker: 'Contact',
    contactTitle: 'Let’s build something useful.',
    contactBody: 'I’m looking for a junior frontend or web-development position where I can contribute to real products, learn from experienced developers, and grow as a frontend engineer.',
    privacy: 'This opens your email app. No form data is stored on this website.',
    backToTop: 'Back to top',
    cvLabel: 'CV (English)',
  },
} as const;

export const processSteps: Record<Language, [string, string, string][]> = {
  de: [
    ['01', 'Verstehen', 'Anforderungen, Nutzer und Geschäftsproblem'],
    ['02', 'Gestalten', 'User Flows, Wireframes und responsive Interfaces'],
    ['03', 'Entwickeln', 'Komponenten, APIs, Daten und Authentifizierung'],
    ['04', 'Liefern', 'Testen, Debugging, Deployment und Iteration'],
  ],
  en: [
    ['01', 'Understand', 'Requirements, users, and business problems'],
    ['02', 'Design', 'User flows, wireframes, and responsive interfaces'],
    ['03', 'Develop', 'Components, APIs, data, and authentication'],
    ['04', 'Deliver', 'Testing, debugging, deployment, and iteration'],
  ],
};

export const projectCopy: Record<string, Record<Language, {
  label: string;
  summary: string;
  problem: string;
  contribution: string;
  decision: string;
  features: string[];
  architecture: string;
  imageAlt: string;
}>> = {
  penee: {
    de: {
      label: '01 · Ausgewähltes Projekt',
      summary: 'Eine Full-Stack-Anwendung für persönliche Finanzen, mit der Nutzer Konten, Transaktionen, Budgets und mehrere Währungen verwalten können. Entwickelt mit Next.js, PostgreSQL und Prisma sowie sitzungsbasierter Authentifizierung und Schutzmechanismen für historische Finanzdaten.',
      problem: 'Finanzanwendungen müssen Konten, Budgets, Währungen und historische Buchungen verwalten, ohne bereits erfasste Finanzdaten unbeabsichtigt zu verändern.',
      contribution: 'Konzeption und Entwicklung des responsiven Interfaces, der serverseitigen Abläufe, der Datenbankschicht, der Authentifizierung und des Deployments.',
      decision: 'Eine Änderung der Basiswährung verändert keine historischen Finanzdaten. Transaktionen behalten ursprünglichen Betrag und Währung; aktuelle Dashboard-Summen können mit aktuellen Wechselkursen neu berechnet werden.',
      features: ['Sitzungsbasierte Authentifizierung und geschützte Routen', 'Konten sowie Einnahmen- und Ausgabentransaktionen', 'Korrekturtransaktionen', 'Budgets und mehrere Währungen', 'Wechselkurse und Dashboard-Zusammenfassungen', 'Ledger, Kontoauszüge und Funktionen zum Zurücksetzen von Daten'],
      architecture: 'Nutzer → Next.js / React → Server Actions und API Routes → Prisma → PostgreSQL',
      imageAlt: 'Anmeldeseite der persönlichen Finanzanwendung Penee',
    },
    en: {
      label: '01 · Featured Project',
      summary: 'A full-stack personal finance application designed to help users manage accounts, transactions, budgets, and multiple currencies. Built with Next.js, PostgreSQL, and Prisma, with session-based authentication and safeguards designed to preserve historical financial data.',
      problem: 'Personal-finance applications must manage accounts, transactions, budgets, currencies, and historical records without unintentionally changing previously recorded financial information.',
      contribution: 'I designed and developed the responsive interface, server-side operations, database layer, authentication flow, and deployment.',
      decision: 'Changing a user’s base-currency preference does not mutate historical financial data. Transactions retain their original amount and currency, while dashboard totals can be recalculated in the selected base currency using current exchange rates.',
      features: ['Session-based authentication and protected routes', 'Accounts plus income and expense transactions', 'Correction transactions', 'Budgets and multi-currency support', 'Exchange rates and dashboard summaries', 'Ledger, statements, and data-reset functionality'],
      architecture: 'User → Next.js / React → Server Actions and API Routes → Prisma → PostgreSQL',
      imageAlt: 'Penee personal finance application secure login screen',
    },
  },
  itemvault: {
    de: {
      label: '02 · Echtzeit-Anwendung',
      summary: 'Eine responsive Anwendung für persönliche Inventare mit Firebase Authentication, Echtzeitdaten aus Firestore und nutzerorientierten Organisationsfunktionen.',
      problem: 'Persönliche Gegenstände sind schwer zu verwalten, wenn Einträge nicht schnell auffindbar sind oder private Daten nicht eindeutig einem Nutzer zugeordnet werden.',
      contribution: 'Entwicklung des React-Interfaces, der Authentifizierung, der Echtzeit-Datenanbindung, geschützter Routen und responsiver Ansichten.',
      decision: 'Firestore Listener halten Inventardaten aktuell. Authentifizierung, geschützte Routen und Firestore Security Rules trennen die privaten Inventare der Nutzer.',
      features: ['Registrierung und Anmeldung', 'Private Nutzerinventare', 'Anlegen von Gegenständen', 'Kategorien, Orte und Status', 'Suche und Filter', 'Dashboard und responsive Layouts'],
      architecture: 'Nutzer → React / Vite → Firebase Authentication → Firestore',
      imageAlt: 'Responsive Startseite der persönlichen Inventaranwendung ItemVault',
    },
    en: {
      label: '02 · Real-Time Application',
      summary: 'A responsive personal inventory application with Firebase authentication, real-time Firestore data, and user-focused organization tools.',
      problem: 'Personal inventories become difficult to use when items cannot be found quickly or private records are not clearly separated by user.',
      contribution: 'I built the React interface, authentication flow, real-time data integration, protected routes, and responsive inventory experience.',
      decision: 'Firestore listeners keep inventory data current. Authentication, protected routes, and Firestore Security Rules separate each user’s private inventory.',
      features: ['Registration and login', 'Private user inventories', 'Item creation', 'Categories, locations, and item status', 'Search and filtering', 'Dashboard and responsive layouts'],
      architecture: 'User → React / Vite → Firebase Authentication → Firestore',
      imageAlt: 'ItemVault responsive personal inventory landing page',
    },
  },
  'cosmic-styles': {
    de: {
      label: '03 · Geschäftsorientierte Anwendung',
      summary: 'Eine responsive Barbershop-Website, die echte Leistungen und Geschäftsinformationen präsentiert und Kunden anschließend durch eine strukturierte Terminanfrage führt.',
      problem: 'Ein lokaler Barbershop muss Leistungen, Preise, Standort und Verfügbarkeit klar zeigen und einen einfachen Weg zur Terminanfrage anbieten.',
      contribution: 'Konzeption und Entwicklung des responsiven Interfaces und der mehrstufigen Buchungsanfrage sowie Anbindung an WhatsApp und einen optionalen E-Mail-Benachrichtigungsweg.',
      decision: 'Die Buchung führt schrittweise von der Leistung über Datum und Uhrzeit zu den Kundendaten. Die Anfrage wird als vorausgefüllte WhatsApp-Nachricht übergeben; eine automatische Bestätigung oder Speicherung wird nicht behauptet.',
      features: ['Leistungen und Preise', 'Standort und Buchungszeiten', 'Responsive Galerie und Navigation', 'Auswahl von Leistung, Datum und Uhrzeit', 'Erfassung der Kundendaten', 'WhatsApp-Übergabe und optionale E-Mail-Benachrichtigung'],
      architecture: 'Nutzer → HTML / CSS / JavaScript → WhatsApp · optional Vercel Function → Resend',
      imageAlt: 'Responsive Website von Cosmic Styles LLC mit schwarzem und goldenem Design',
    },
    en: {
      label: '03 · Business-Focused Application',
      summary: 'A responsive barbershop website that presents real services and business information, then guides customers through a structured appointment request.',
      problem: 'A local barbershop needs to communicate its services, pricing, location, and availability while giving customers a clear path to request an appointment.',
      contribution: 'I designed and built the responsive interface and multi-step appointment request, connecting it to WhatsApp and an optional email-notification path.',
      decision: 'The flow progresses from service to date and time to customer details. It hands off a prefilled WhatsApp request; no database persistence or automatic confirmation is claimed.',
      features: ['Services and pricing', 'Location and booking hours', 'Responsive gallery and navigation', 'Service, date, and time selection', 'Customer-detail collection', 'WhatsApp handoff and optional email notification'],
      architecture: 'User → HTML / CSS / JavaScript → WhatsApp · optional Vercel Function → Resend',
      imageAlt: 'Cosmic Styles LLC responsive barbershop website in black and gold',
    },
  },
};

export const skillGroups: Array<{ title: Bilingual; skills: string[]; evidence?: Bilingual }> = [
  { title: { de: 'Frontend', en: 'Frontend' }, skills: ['React', 'Next.js', 'TypeScript', 'JavaScript', 'HTML', 'CSS', 'Tailwind CSS', 'Vite'], evidence: { de: 'React: Penee & ItemVault · Next.js: Penee · HTML/CSS/JavaScript: Cosmic Styles', en: 'React: Penee & ItemVault · Next.js: Penee · HTML/CSS/JavaScript: Cosmic Styles' } },
  { title: { de: 'Full-Stack', en: 'Full-stack' }, skills: ['Node.js', 'Express', 'REST APIs', 'Next.js Server Actions'] },
  { title: { de: 'Datenbanken', en: 'Databases' }, skills: ['PostgreSQL', 'Prisma', 'Firebase / Firestore', 'MongoDB'], evidence: { de: 'PostgreSQL & Prisma: Penee · Firebase & Firestore: ItemVault', en: 'PostgreSQL & Prisma: Penee · Firebase & Firestore: ItemVault' } },
  { title: { de: 'Authentifizierung & Sicherheit', en: 'Authentication & security' }, skills: ['Session-based Authentication', 'Authorization', 'bcrypt', 'HTTP-only Cookies', 'Protected Routes', 'Ownership Checks', 'Firestore Security Rules'] },
  { title: { de: 'UI/UX', en: 'UI/UX' }, skills: ['Figma', 'UI Design', 'UX Design', 'Wireframes', 'Prototypes', 'User Flows', 'Personas', 'Empathy Maps', 'Sitemaps', 'Information Architecture', 'Responsive Interface Design'] },
  { title: { de: 'Werkzeuge', en: 'Tools' }, skills: ['Git', 'GitHub', 'VS Code', 'npm', 'Docker', 'Vercel', 'ngrok'] },
  { title: { de: 'Entwicklungspraxis', en: 'Development practices' }, skills: ['CRUD', 'API Integration', 'Database Design', 'Debugging', 'Requirements Analysis', 'Technical Documentation', 'Scrum', 'Agile Development'] },
];

export const strengths: Record<Language, string[]> = {
  de: ['Problemlösung', 'Geschäftsverständnis', 'Ruhige Kommunikation', 'Verlässliche Umsetzung', 'Teamarbeit', 'Strukturiertes Denken', 'Verantwortung', 'Lernbereitschaft'],
  en: ['Problem solving', 'Business awareness', 'Calm communication', 'Dependable delivery', 'Team collaboration', 'Structured thinking', 'Ownership', 'Willingness to learn'],
};

export const experience: Array<{ date: Bilingual; kind: Bilingual; title: string; org?: string; body: Bilingual; modules?: Array<[string, Bilingual]> }> = [
  {
    date: { de: '09/2025 – voraussichtlich 09/2026', en: '09/2025 – expected 09/2026' },
    kind: { de: 'IT-Qualifizierung · 2.300 UE', en: 'IT qualification · 2,300 units' },
    title: 'Qualifizierung zur IT-Fachkraft',
    org: 'Syntax Institut',
    body: { de: 'Projektbasierte Weiterbildung in Produktdesign, UI/UX, Software- und Webentwicklung, Frontend-Entwicklung, Backend-Grundlagen, Datenbanken, Authentifizierung, APIs, Git/GitHub, Deployment, agilem Arbeiten und technischer Dokumentation.', en: 'Project-based training in product design, UI/UX, software and web development, frontend development, backend fundamentals, databases, authentication, APIs, Git/GitHub, deployment, agile work, and technical documentation.' },
    modules: [
      ['700 UE', { de: 'Produktdesign & -entwicklung in der IT', en: 'Product design & IT product development' }],
      ['600 UE', { de: 'Einführung Software- und Webentwicklung', en: 'Introduction to software & web development' }],
      ['500 UE', { de: 'Vertiefung Frontend Entwicklung', en: 'Advanced frontend development' }],
      ['500 UE', { de: 'Spezialisierung & Arbeitsmarktvorbereitung', en: 'Specialization & career preparation' }],
    ],
  },
  { date: { de: '2023 – 2025', en: '2023 – 2025' }, kind: { de: 'Mitarbeiter Logistik', en: 'Logistics Operations Associate' }, title: 'Preymesser', body: { de: 'Unterstützung von Lager- und Transportabläufen durch Be- und Entladung sowie Materialhandhabung. Zusammenarbeit mit operativen Teams für sichere und verlässliche Arbeitsabläufe.', en: 'Supported warehouse and transport operations through loading, offloading, and material handling, working with operational teams to maintain safe and reliable workflows.' } },
  { date: { de: '2022 – 2023', en: '2022 – 2023' }, kind: { de: 'Mitarbeiter Industrielogistik', en: 'Industrial Logistics Operator' }, title: 'Haeger & Schmidt', body: { de: 'Be- und Entladung von Lkw und Schiffen, krangestützte Materialhandhabung, Schneidarbeiten und Pflege des Arbeitsbereichs in einem sicherheitsorientierten Industrieumfeld.', en: 'Performed truck and vessel loading and offloading, crane-assisted material handling, blade cutting, and work-area maintenance within a safety-focused industrial environment.' } },
  { date: { de: '2007 – 2021', en: '2007 – 2021' }, kind: { de: 'Einkaufsmanager · Internationale Beschaffung & SAP', en: 'Purchasing Manager · International Procurement & SAP' }, title: 'SIB Enterprises', body: { de: 'Verantwortung für Einkauf und Beschaffung einschließlich internationaler Lieferantensuche und Geschäftskommunikation. Nutzung von SAP für Einkaufsabläufe, Bestellungen, Lieferantendaten und Administration sowie Koordination von Import und Export.', en: 'Managed purchasing and procurement, including international supplier sourcing and business coordination. Used SAP for purchasing workflows, orders, supplier records, and procurement administration while coordinating import and export activities.' } },
];

export const qualifications = [
  { title: 'Produktdesign & -entwicklung in der IT', institution: 'Syntax Institut', date: '08.01.2026', subject: { de: '700 UE · Designprinzipien, Informationsarchitektur, Personas, User Flows, Wireframes, Prototyping, Scrum, Figma und Framer', en: '700 units · Design principles, information architecture, personas, user flows, wireframes, prototyping, Scrum, Figma, and Framer' }, href: '/certificates/produktdesign-it-web.pdf' },
  { title: 'Digital Product Designer IHK', institution: 'IHK Akademie München und Oberbayern gGmbH', date: '15.01.2026', subject: { de: '250 Unterrichtsstunden · UI/UX-Grundlagen, Wireframing, Prototyping, User Research und Scrum', en: '250 hours · UI/UX fundamentals, wireframing, prototyping, user research, and Scrum' }, href: '/certificates/digital-product-designer-ihk-web.pdf' },
  { title: 'Einführung Software- und Webentwicklung', institution: 'Syntax Institut', date: '02.04.2026', subject: { de: '600 UE · HTML, CSS, Bootstrap, JavaScript, Responsive Design, APIs, Code-Editoren und Git', en: '600 units · HTML, CSS, Bootstrap, JavaScript, responsive design, APIs, code editors, and Git' }, href: '/certificates/software-webentwicklung-web.pdf' },
  { title: 'Vertiefung: Frontend Entwicklung', institution: 'Syntax Institut', date: '26.06.2026', subject: { de: '500 UE · React, Vite, Tailwind CSS, TypeScript, Firebase, Firestore, Strapi und Vercel', en: '500 units · React, Vite, Tailwind CSS, TypeScript, Firebase, Firestore, Strapi, and Vercel' }, href: '/certificates/frontend-entwicklung-web.pdf' },
];
